name: Docker Build & Push
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get commit SHA
        id: extract_commit_sha
        run: echo "::set-output name=commit_sha::${{ github.sha }}" 

      - name: Get original image tag
        id: extract_tag
        run: |
          # Extract the base image tag from the Dockerfile
          DOCKERFILE_CONTENT=$(cat Dockerfile)
          TAG_REGEX="FROM rocker/geospatial:([^[:space:]]+)"
          ORIGINAL_TAG=$(echo "$DOCKERFILE_CONTENT" | grep -oE "$TAG_REGEX" | awk -F ":" '{print $2}')
          if [[ -n $ORIGINAL_TAG ]]; then
            echo "::set-output name=tag::$ORIGINAL_TAG"
          else
            echo "Failed to extract the tag from the Dockerfile"
            exit 1
          fi

      - name: Determine new tag
        id: generate_tag
        run: |
          # Extract the first 7 characters from the commit SHA
          COMMIT_SHA_SHORT=$(echo ${{ steps.extract_commit_sha.outputs.commit_sha }} | cut -c1-7)

          # Combine the original tag and the first 7 characters of the commit SHA
          NEW_TAG="${{ steps.extract_tag.outputs.tag }}-${COMMIT_SHA_SHORT}"
          echo "::set-output name=tag::$NEW_TAG"
       
      # Use github actions https://github.com/marketplace/actions/free-disk-space-ubuntu 
      #  See also SO post: https://github.com/orgs/community/discussions/26351#discussioncomment-3251595
      # - name: Free Disk Space (Ubuntu)
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     # this might remove tools that are actually needed,
      #     # if set to "true" but frees about 6 GB
      #     tool-cache: false
      #   
      #     # all of these default to true, but feel free to set to
      #     # "false" if necessary for your workflow
      #     android: true
      #     dotnet: true
      #     haskell: true
      #     large-packages: true
      #     swap-storage: true

      - name: Build and push Docker image
        run: |
          # Build the new Docker image with the combined tag
          docker build -t rmgpanw/geospatial:${{ steps.generate_tag.outputs.tag }} .

          # Push the new Docker image
          docker push rmgpanw/geospatial:${{ steps.generate_tag.outputs.tag }}
