name: Docker Build & Push
on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag name
        id: image_tag
        run: |
          # tag name
          TAG_BASE="rmgpanw/rwd"
          TAG_NAME="${TAG_BASE}:$(cat VERSION.md)"
          TAG_NAME_DEV="${TAG_BASE}:$(cat VERSION.md)-dev"
          echo "::set-output name=tag_base::${TAG_BASE}" 
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=tag_name_dev::${TAG_NAME_DEV}"

      - name: Build and push latest
        uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          push: true
          tags: ${{ steps.image_tag.outputs.tag_name }} , ${{ steps.image_tag.outputs.tag_base }}:latest
          cache-from: type=registry,ref=${{ steps.image_tag.outputs.tag_name }}
          cache-to: type=inline

      - name: Build and push dev
        uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/dev'
        with:
          context: .
          push: true
          tags: ${{ steps.image_tag.outputs.tag_name_dev }}
          cache-from: type=registry,ref=${{ steps.image_tag.outputs.tag_name_dev }}
          cache-to: type=inline
